// <auto-generated>
// Generated from the FlagDatabase asset via Tools > Game > Generate World Flag Constants.
// Do not edit by hand — your changes will be overwritten.
// </auto-generated>

public static partial class WorldFlags
{
    public static class Location
    {
        public static class Cafe
        {
            public const string Unlocked = "location.Cafe.unlocked";

            public const string Visited = "location.Cafe.visited";
        }

        public static class WorkFirstFloor
        {
            public const string Unlocked = "location.Work_FirstFloor.unlocked";

            public const string Visited = "location.Work_FirstFloor.visited";
        }

        public static class WorkSecondFloor
        {
            public const string Unlocked = "location.Work_SecondFloor.unlocked";

            public const string Visited = "location.Work_SecondFloor.visited";
        }
    }

    public static class Npc
    {
        public static class Bob
        {
            public const string Befriended = "npc.Bob.befriended";

            public const string Helped = "npc.Bob.helped";

            public const string IntroSeen = "npc.Bob.intro_seen";

            public const string Met = "npc.Bob.met";

            public const string Upset = "npc.Bob.upset";
        }

        public static class Cat
        {
            public const string Befriended = "npc.Cat.befriended";

            public const string Helped = "npc.Cat.helped";

            public const string IntroSeen = "npc.Cat.intro_seen";

            public const string Met = "npc.Cat.met";

            public const string Upset = "npc.Cat.upset";
        }
    }

    public static class Tutorial
    {
        public static class Dialogue
        {
            public const string Seen = "tutorial.dialogue.seen";
        }

        public static class Inventory
        {
            public const string Seen = "tutorial.inventory.seen";
        }

        public static class Journal
        {
            public const string Seen = "tutorial.journal.seen";
        }

        public static class SaveLoad
        {
            public const string Seen = "tutorial.save_load.seen";
        }

        public static class Time
        {
            public const string Seen = "tutorial.time.seen";
        }
    }
}
