using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

/// <summary>
/// Writes WorldFlags.Generated.cs from the FlagDatabase so code can reference flags
/// as compile-time constants (e.g. WorldFlags.Npc.Bob.Met) instead of raw strings.
/// Regenerate after adding flags, NPCs or locations. Renaming an entity then breaks
/// stale code references at compile time — which is the point.
/// </summary>
public static class WorldFlagConstantsGenerator
{
    private const string OutputPath = "Assets/Scripts/WorldFlags.Generated.cs";

    [MenuItem("Tools/Game/Generate World Flag Constants")]
    public static void Generate()
    {
        var db = WorldFlagEditorUtility.GetOrCreateDatabase();
        if (db == null)
            return;

        var ids = db.GetAllFlagIds()
            .Where(id => !string.IsNullOrWhiteSpace(id))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(id => id, StringComparer.Ordinal)
            .ToList();

        var root = new Node();
        foreach (string id in ids)
            Insert(root, id);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated from the FlagDatabase asset via Tools > Game > Generate World Flag Constants.");
        sb.AppendLine("// Do not edit by hand — your changes will be overwritten.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("public static partial class WorldFlags");
        sb.AppendLine("{");
        EmitChildren(sb, root, 1);
        sb.AppendLine("}");

        string content = sb.ToString();
        string fullPath = Path.GetFullPath(OutputPath);

        if (File.Exists(fullPath) && File.ReadAllText(fullPath) == content)
        {
            Debug.Log($"[WorldFlags] Constants already up to date ({ids.Count} flags).");
            return;
        }

        File.WriteAllText(fullPath, content);
        AssetDatabase.ImportAsset(OutputPath);
        Debug.Log($"[WorldFlags] Generated {ids.Count} flag constants into {OutputPath}.");
    }

    // ── Id tree ───────────────────────────────────────────────────────────

    private sealed class Node
    {
        public readonly SortedDictionary<string, Node> Children = new(StringComparer.Ordinal);
        public string FlagId; // set when this node itself is a complete flag id
    }

    private static void Insert(Node root, string flagId)
    {
        var node = root;
        foreach (string segment in flagId.Split('.'))
        {
            if (string.IsNullOrWhiteSpace(segment))
                continue;

            if (!node.Children.TryGetValue(segment, out var child))
            {
                child = new Node();
                node.Children[segment] = child;
            }

            node = child;
        }

        node.FlagId = flagId;
    }

    private static void EmitChildren(StringBuilder sb, Node node, int depth)
    {
        string indent = new string(' ', depth * 4);
        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        bool first = true;

        foreach (var kv in node.Children)
        {
            if (!first)
                sb.AppendLine();
            first = false;

            string name = UniqueName(ToIdentifier(kv.Key), usedNames);
            var child = kv.Value;

            if (child.Children.Count == 0)
            {
                // Leaf — plain const.
                sb.AppendLine($"{indent}public const string {name} = \"{child.FlagId}\";");
                continue;
            }

            sb.AppendLine($"{indent}public static class {name}");
            sb.AppendLine($"{indent}{{");

            // Node is both a flag and a group (e.g. "npc.bob" and "npc.bob.met").
            if (!string.IsNullOrEmpty(child.FlagId))
            {
                sb.AppendLine($"{indent}    public const string _Self = \"{child.FlagId}\";");
                sb.AppendLine();
            }

            EmitChildren(sb, child, depth + 1);
            sb.AppendLine($"{indent}}}");
        }
    }

    // ── Identifier helpers ────────────────────────────────────────────────

    private static string ToIdentifier(string segment)
    {
        var sb = new StringBuilder(segment.Length);
        bool upperNext = true;

        foreach (char c in segment)
        {
            if (char.IsLetterOrDigit(c))
            {
                sb.Append(upperNext ? char.ToUpperInvariant(c) : c);
                upperNext = false;
            }
            else
            {
                upperNext = true; // '_', '-', etc. act as word breaks
            }
        }

        if (sb.Length == 0)
            return "_";

        if (char.IsDigit(sb[0]))
            sb.Insert(0, '_');

        return sb.ToString();
    }

    private static string UniqueName(string name, HashSet<string> used)
    {
        string candidate = name;
        int suffix = 2;

        while (!used.Add(candidate))
            candidate = name + suffix++;

        return candidate;
    }
}
